### ISSUE TITLE
SoftImpute Batch Processing option on huge dataset

### ISSUE THREAD

**Issue by prathmeshgat** [iskandr/fancyimpute#58]
I am trying to use softimpute library to replace missing entries from the dataset. But my dataset size is very large to fit into memory. Does this library provide the batch processing option? If not how should I use this library on the huge dataset to replace missing attributes in records?

**Comment by sergeyf** [comment]
softimpute uses a batch method, so that won't work with your giant dataset.  However, the `MatrixFactorization` method is currently using SGD. All you have to do is modify the `fit` method to `fit_generator` which loads random samples from disk or something like that: https://github.com/iskandr/fancyimpute/blob/master/fancyimpute/matrix_factorization.py#L100
